#!/bin/sh

REPOS="$1"
TXN="$2"

# Check log message text format.
SVNLOOK=/usr/bin/svnlook
$SVNLOOK log -t "$TXN" "$REPOS" | \
  grep "refs #[0-9][0-9]*[^a-zA-Z0-9]*\|refactor" > /dev/null || \
  { echo "Message format is wrong. ex: (refs #001) commit message." 1>&2 && exit 1;}

# All checks passed, so allow the commit.
exit 0
