# master playbook
- name: Install_Redmine
  hosts: all
  user: vagrant
  sudo: yes
  roles:
    - redmine
  vars_prompt:
    - name: "redmine_db_passwd"
      prompt: "Please enter MySQL wordpress user password"
      default: "redmine"
